---
- name: Log in to Docker Hub
  become: yes
  docker_login:
    username: shashi@gmail.com
    password: Shashi123456
    registry_url: https://index.docker.io/v1/
  register: docker_login_result


- name: Deploy Spring Boot App
  become: yes
  shell: docker run -p 8092:8080 shashikrpet/spring:2.0
  notify: Restart Spring Boot App
